name: Android CI
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Install Android SDK components
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "platform-tools"

      # 可选：看看 Gradle/Java 环境
      - name: Print Gradle env
        working-directory: NavSwitcher
        run: ./gradlew -v

      # 干净构建，避免缓存旧报错
      - name: Clean
        working-directory: NavSwitcher
        run: ./gradlew clean

      # 关键：把所有输出 tee 到 buildlog.txt；失败也会留下日志
      - name: Build Debug APK (Gradle 8.7) with full logs
        working-directory: NavSwitcher
        env:
          TERM: xterm-256color
        run: |
          set -euxo pipefail
          ./gradlew :app:assembleDebug --stacktrace --info --warning-mode all 2>&1 | tee buildlog.txt

      # 无论成功失败都上传日志，Artifacts 里能下载到
      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: buildlog
          path: NavSwitcher/buildlog.txt

      # 成功时把 APK 也传出来（用通配更稳）
      - name: Upload debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: NavSwitcher/app/build/outputs/apk/debug/*.apk
