name: Android CI
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # 一步装好 Android 命令行工具（比手撸 curl+unzip 稳）
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          set -euxo pipefail
          sdkmanager --licenses <<< "y"
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"


      # 看看仓库结构（诊断用）
      - name: List repo
        run: |
          pwd
          ls -la
          ls -la NavSwitcher || true
          ls -la NavSwitcher/gradle || true
          ls -la NavSwitcher/gradle/wrapper || true

      - name: Make gradlew executable (if present)
        run: |
          if [ -f NavSwitcher/gradlew ]; then chmod +x NavSwitcher/gradlew; fi

      - name: Print Gradle env
        run: |
          set -euxo pipefail
          if [ -x NavSwitcher/gradlew ]; then
            (cd NavSwitcher && ./gradlew -v)
          else
            echo "::warning::gradlew not found; using global Gradle"
            gradle -v
          fi

      - name: Clean
        run: |
          set -euxo pipefail
          if [ -x NavSwitcher/gradlew ]; then
            (cd NavSwitcher && ./gradlew clean)
          else
            (cd NavSwitcher && gradle clean)
          fi

      # 关键：把日志 tee 到文件，并强制 Kotlin 编译器 in-process、纯文本输出
      - name: Build Debug APK (full log to file)
        env:
          TERM: xterm-256color
        run: |
          set -euxo pipefail
          # 统一的 Gradle 参数，确保日志完整：
          #  - --no-configuration-cache  避免缓存掩盖错误
          #  - --console=plain           纯文本控制台，去掉花色
          #  - -Dkotlin.colors.enabled=false  关闭彩色，便于 grep
          #  - -Dkotlin.compiler.execution.strategy=in-process  让 Kotlin 不走 workers，直接在进程内打印诊断
          COMMON_OPTS="--stacktrace --info --warning-mode all --no-configuration-cache --console=plain -Dkotlin.colors.enabled=false -Dkotlin.compiler.execution.strategy=in-process"

          if [ -x NavSwitcher/gradlew ]; then
            (cd NavSwitcher && ./gradlew :app:assembleDebug $COMMON_OPTS) 2>&1 | tee buildlog.txt
          else
            (cd NavSwitcher && gradle :app:assembleDebug $COMMON_OPTS) 2>&1 | tee buildlog.txt
          fi

      # 如果失败，单独抽取 Kotlin 编译错误的 “e: …” 行，方便定位
      - name: Extract Kotlin errors
        if: failure()
        run: |
          echo "===== Kotlin compiler errors (grep '^e: ') ====="
          grep -n "^e: " NavSwitcher/buildlog.txt || true
          echo "===== End ====="

      # 失败时多打点：把 Kotlin/AAPT 报告目录都打包，便于排查
      - name: Upload build reports & logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            NavSwitcher/buildlog.txt
            NavSwitcher/app/build/reports/**
            NavSwitcher/app/build/tmp/kotlin-compile/**
            NavSwitcher/app/build/outputs/logs/**
            NavSwitcher/app/build/outputs/apk/debug/**

      - name: Upload debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: NavSwitcher/app/build/outputs/apk/debug/*.apk
