name: Android CI
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Install Android SDK components
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "platform-tools"

      # —— 诊断：看看仓库和子目录里到底有什么 ——
      - name: List repo root
        run: |
          pwd
          ls -la

      - name: List NavSwitcher contents
        run: |
          ls -la NavSwitcher || true
          ls -la NavSwitcher/gradle || true
          ls -la NavSwitcher/gradle/wrapper || true

      # 给 gradlew 授权（存在才授权，不存在不报错）
      - name: Make gradlew executable (if present)
        run: |
          if [ -f NavSwitcher/gradlew ]; then
            chmod +x NavSwitcher/gradlew
          fi

      # 打印 Gradle 环境：优先用 wrapper；没有就用全局 gradle
      - name: Print Gradle env
        run: |
          set -euxo pipefail
          if [ -x NavSwitcher/gradlew ]; then
            (cd NavSwitcher && ./gradlew -v)
          else
            echo "::warning::gradlew not found; using global Gradle"
            gradle -v
          fi

      # 干净构建
      - name: Clean
        run: |
          set -euxo pipefail
          if [ -x NavSwitcher/gradlew ]; then
            (cd NavSwitcher && ./gradlew clean)
          else
            (cd NavSwitcher && gradle clean)
          fi

      # 关键：把日志 tee 到文件，失败也能下载
      - name: Build Debug APK with full logs
        env:
          TERM: xterm-256color
        run: |
          set -euxo pipefail
          if [ -x NavSwitcher/gradlew ]; then
            (cd NavSwitcher && ./gradlew :app:assembleDebug --stacktrace --info --warning-mode all 2>&1 | tee buildlog.txt)
          else
            (cd NavSwitcher && gradle :app:assembleDebug --stacktrace --info --warning-mode all 2>&1 | tee buildlog.txt)
          fi

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: buildlog
          path: NavSwitcher/buildlog.txt

      - name: Upload debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: NavSwitcher/app/build/outputs/apk/debug/*.apk
