name: Android CI
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK components
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Build Debug APK with Gradle 8.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
          arguments: assembleDebug
          build-root-directory: NavSwitcher   # ← 关键：工程所在子目录

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: NavSwitcher/app/build/outputs/apk/debug/app-debug.apk  # ← 路径也要带子目录
