name: Android CI
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # 一步装好 Android 命令行工具（比手撸 curl+unzip 稳）
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          set -euxo pipefail
          sdkmanager --licenses <<< "y"
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"


      # 看看仓库结构（诊断用）
      - name: List repo
        run: |
          pwd
          ls -la
          ls -la NavSwitcher || true
          ls -la NavSwitcher/gradle || true
          ls -la NavSwitcher/gradle/wrapper || true

      - name: Make gradlew executable (if present)
        run: |
          if [ -f NavSwitcher/gradlew ]; then chmod +x NavSwitcher/gradlew; fi

      - name: Print Gradle env
        run: |
          set -euxo pipefail
          if [ -x NavSwitcher/gradlew ]; then
            (cd NavSwitcher && ./gradlew -v)
          else
            echo "::warning::gradlew not found; using global Gradle"
            gradle -v
          fi

      - name: Clean
        run: |
          set -euxo pipefail
          if [ -x NavSwitcher/gradlew ]; then
            (cd NavSwitcher && ./gradlew clean)
          else
            (cd NavSwitcher && gradle clean)
          fi

      # 关键：无论成功失败，都把完整日志保存出来
      - name: Build Debug APK (full log to file)
        continue-on-error: true
        run: |
          set -euxo pipefail
          if [ -x NavSwitcher/gradlew ]; then
            (cd NavSwitcher && ./gradlew :app:assembleDebug --stacktrace --info --warning-mode all) 2>&1 | tee NavSwitcher/buildlog.txt
          else
            (cd NavSwitcher && gradle :app:assembleDebug --stacktrace --info --warning-mode all) 2>&1 | tee NavSwitcher/buildlog.txt
          fi

      # 如果失败，单独抽取 Kotlin 编译错误的 “e: …” 行，方便定位
      - name: Extract Kotlin errors
        if: failure()
        run: |
          echo "===== Kotlin compiler errors (grep '^e: ') ====="
          grep -n "^e: " NavSwitcher/buildlog.txt || true
          echo "===== End ====="

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: buildlog
          path: NavSwitcher/buildlog.txt

      - name: Upload debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: NavSwitcher/app/build/outputs/apk/debug/*.apk
